name: Meshat Monitor
slug: meshat_monitor
description: Stores Meshtastic MQTT packets locally and presents a compact dashboard
version: "0.1.8"
arch:
  - aarch64
  - amd64
ingress: true
ingress_port: 8099
options:
  topic: "msh/#"
  retention_days: 3
  reset_database: false
  log_mqtt_events: false
schema:
  topic: str
  retention_days: int(1,30)
  reset_database: bool
  log_mqtt_events: bool
init: false
startup: services